zevoyo/chat/urls.py
from django.urls import path
from . import views as v

urlpatterns = [
    path('all/', v.chatList, name='all'),
    path('new/', v.newChat, name='new'),
]

zevoyo/myApp/urls.py
from django.urls import path, include

from . import views

from chat import urls as chat_urls

urlpatterns = [

    path('', views.homePage, name = "homePage"),
    path('home/', views.homePage,name="homepage"),
    path('contact/', views.contactpage, name = "contactpage"),
    path('about/', views.aboutpage, name = "aboutpage"),      
    path('user/', views.user_log_sign_page, name = "userlogin"),
    path('user/login/', views.user_log_sign_page, name = "userlogin"),
    path('user/signup/', views.user_sign_up,name = "usersignup"),
    path('user/editProfile/', views.editProfile,name = "editProfile"),

    path('user/book-room/', views.bookRoomPage, name = "bookRoomPage"),
    path('user/book-room/book/', views.bookRoom, name = "bookRoom"),
    path('user/bookings/', views.user_bookings,name="dashboard"),
    path('user/description/', views.description, name = "description"),

    path('user/add-review/', views.review, name = "review"),

    path('staff/', views.staffSignup, name="staff"),
    path('staff/login/', views.staffLogin, name = "stafflogin"),
    path('staff/signup/', views.staffSignup, name="staffsignup"),
    path('staff/dashboard/', views.dashboard, name = 'staffDashboard'),
    path('staff/searchDashboard/', views.searchDashboard, name = 'searchDashboard'),
    path('staff/dashboard/add-new-location/', views.addNewLocation, name='addNewLocation'),
    path('staff/dashboard/add-new-room/', views.addNewRoom, name='addNewRoom'),
    path('staff/dashboard/edit-room/', views.editRoom, name = "editRoom"),
    path('staff/dashboard/edit-room/edit/', views.editRoom, name = "editRoom"),
    path('staff/dashboard/view-room/', views.viewRoom, name = 'viewRoom'),
    path('staff/allbookings/', views.allBookings, name = 'allBookings'),
    path('staff/users/', views.allUsers, name = 'users'),

    path('filter/', views.filter, name = 'filter'),
    path('booking/cancel/', views.cancelBooking, name = 'cancelBookig'),
    path('logout/', views.logoutUser, name = "logout"),

    path('chat/', include(chat_urls)),
]

zevoyo/zevoyo/urls.py
from django.contrib import admin
from django.urls import path, include

# from myApp import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myApp/',include('myApp.urls')),
]

zevoyo/myApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator, MinLengthValidator

# Create your models here.

class Hotels(models.Model):
    name = models.CharField(max_length = 30)
    owner = models.CharField(max_length = 30)
    type = models.CharField(max_length = 30)
    contactNumber = models.CharField(max_length = 30)
    address = models.CharField(max_length = 50)
    city = models.CharField(max_length = 20)
    state = models.CharField(max_length = 15)
    country = models.CharField(max_length = 20)
    pincode = models.IntegerField(validators=[MaxLengthValidator(6),MinLengthValidator(6)])

    def __str__(self):
        return self.name

class Rooms(models.Model):
    ROOM_STATUS = (
        ('Available', 'Available'),
        ('Not Available', 'Not Available')
    )

    ROOM_TYPE = (
        ('Premium', 'Premium'),
        ('Deluxe', 'Deluxe'),
        ('Basic', 'Basic')
    )

    roomType = models.CharField(max_length = 50, choices = ROOM_TYPE)
    capacity = models.IntegerField()
    price = models.IntegerField()
    size = models.IntegerField()
    bedType = models.CharField(max_length = 30)
    tv = models.CharField(max_length = 30)
    refrigerator = models.CharField(max_length = 30)
    ac = models.CharField(max_length = 30)
    balcony = models.CharField(max_length = 30)
    parking = models.BooleanField()
    description = models.CharField(max_length = 300)
    hotel = models.ForeignKey(Hotels, on_delete = models.CASCADE)
    status = models.CharField(choices = ROOM_STATUS, max_length = 15)
    roomNumber = models.IntegerField()

    def __str__(self):
        return self.hotel.name

class Reservation(models.Model):
    RESERVATION_STATUS = (
        ('Booked', 'Booked'),
        ('Cancelled', 'Cancelled')
    )

    checkIn = models.DateField(auto_now = False)
    checkOut = models.DateField()
    room = models.ForeignKey(Rooms, on_delete = models.CASCADE)
    guest = models.ForeignKey(User, on_delete = models.CASCADE)
    status = models.CharField(choices = RESERVATION_STATUS, max_length = 15)
    cancel = models.BooleanField()
    bookingId = models.CharField(max_length = 100, default = 'null')

    def __str__(self):
        return self.guest.username

class Pnumber(models.Model):
    phone_no = models.IntegerField(validators=[MaxLengthValidator(10),MinLengthValidator(10)])
    user = models.ForeignKey(User, on_delete = models.CASCADE)

class Review(models.Model):
    rating = models.FloatField()
    comment = models.CharField(max_length = 100)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    room = models.ForeignKey(Rooms, on_delete = models.CASCADE)

zevoyo/myApp/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import Hotels, Reservation, Rooms, Pnumber

from zevoyo.settings import EMAIL_HOST_USER

import datetime
import json

def homePage(request):
    all_location = Hotels.objects.values_list('city', flat=True).distinct().order_by()
    if request.method =="POST":
        try:
            
            hotel = Hotels.objects.all().filter(city=request.POST['search_location'])
            rr = []
            
            #for finding the reserved rooms on this time period for excluding from the query set
            for reservation in Reservation.objects.all():

                if (str(reservation.checkIn) > str(request.POST['cout']) or str(reservation.checkOut) < str(request.POST['cin'])) or reservation.status == 'Cancelled':
                    pass
                else:
                    rr.append(reservation.room.id)
                
            room = Rooms.objects.all().filter(hotel__city=hotel[0].city,capacity__gte = int(request.POST['capacity'])).exclude(id__in=rr)
            room = room.filter(status = 'Available')

            if len(room) == 0:
                messages.warning(request,"Sorry No Rooms Are Available on this time period")
            data = {'rooms':room,'all_location':all_location,'flag':True}
            
            response = render(request,'index.html', data)
        except Exception as e:
            messages.error(request,e)
            response = render(request,'index.html',{'all_location':all_location})
    else:
        data = {'all_location':all_location}
        response = render(request,'index.html',data)
    return HttpResponse(response)

def contactpage(request):
    return HttpResponse(render(request,'contact.html'))

def aboutpage(request):
    hotels = Hotels.objects.all()
    rooms = Rooms.objects.all()
    cities = Hotels.objects.values_list('city', flat = True).distinct().order_by()
    response = render(request, 'about.html', {'cities': len(cities), 'rooms': len(rooms), 'hotels': len(hotels)})
    return HttpResponse(response)
    
def description(request):
    room = Rooms.objects.all().get(id = int(request.GET['roomid']))
    return HttpResponse(render(request, "description.html", {"room": room}))

def review(request):
    room = Rooms.objects.all().get(id = int(request.GET['roomid']))

def staffSignup(request):
    if request.method == 'POST':
        userName = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 != password2:
            messages.success(request, "Password didn't match")
            return redirect('stafflogin')
        try:
            if User.objects.all().get(username = userName):
                messages.warning(request, "Username already exist")
                return redirect('stafflogin')
        except:
            try:
                if User.objects.all().get(email=email):
                    messages.warning(request,"email is not available")
                    return redirect('userlogin')
            except:
                pass   

        newUser = User.objects.create_user(username = userName, password = password1, email = email)
        newUser.is_superuser = False
        newUser.is_staff = True

        phone = Pnumber()
        phone.user = newUser
        phone.phone_no = None
        phone.save()
        newUser.save()

        subject = 'Staff Account Confirmation'
        message = 'Your account has been created successfully.\nUsername: ' + userName + '\nEmail: ' + email
        sendEmail(email, subject, message)

        messages.success(request, 'Staff Registration Successfull')

        return redirect('stafflogin')
    else:
        return render(request, 'staff/login.html')

def staffLogin(request):
    if request.method == 'POST':
        userName = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username = userName, password = password)

        if user is not None and user.is_staff == True:
            login(request, user)
            return redirect('homePage')
        elif user is not None and user.is_staff == False:
            messages.success(request, 'User is not a staff member')
            return redirect('stafflogin')
        else:
            messages.error(request, 'Incorrect username or password')
            return redirect('stafflogin')
    return render(request, 'staff/login.html')

def user_sign_up(request):
    if request.method=="POST":
        email = request.POST['email']
        userName = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        
        if password1 != password2:
            messages.warning(request,"Password didn't matched")
            return redirect('userlogin')
        try:
            if User.objects.all().get(username=userName):
                messages.warning(request,"username is not available")
                return redirect('userlogin')
            
        except:
            try:
                if User.objects.all().get(email = email):
                    messages.warning(request,"email is not available")
                    return redirect('userlogin')
            except:
                pass

        new_user = User.objects.create_user(username = userName, password = password1, email=email)
        new_user.is_superuser=False
        new_user.is_staff=False
        

        phone = Pnumber()
        phone.user = new_user
        phone.phone_no = 0
        phone.save()
        new_user.save()

        subject = 'Account Confirmation'
        message = 'Your account has been created successfully.\nUsername: ' + userName + '\nEmail: ' + email
        sendEmail(email, subject, message)

        messages.success(request,"Registration Successfull")
        return redirect("userlogin")
    else:
        return render(request, 'user/login.html')

def user_log_sign_page(request):
    if request.method == 'POST':
        userName = request.POST['username']
        password = request.POST['password']

        user = authenticate(request,username=userName,password=password)
        try:
            if user.is_staff:
                
                messages.error(request,"Incorrect username or Password")
                return redirect('stafflogin')
        except:
            pass
            
        if user is not None:
            login(request,user)
            messages.success(request,"successful logged in")
            return redirect('homePage')
        else:
            messages.warning(request,"Incorrect username or password")
            return redirect('userlogin')
    
    return render(request,'user/login.html')

def logoutUser(request):
    logout(request)
    return redirect('/myApp/user/')

def editProfile(request):

    try:
        existingUser = User.objects.get(id = request.user.id)
    except User.DoesNotExist:
        existingUser = ""

    try:
        Pnumber1 =  Pnumber.objects.get(user = existingUser)
    except Pnumber.DoesNotExist:
        Pnumber1 = ""

    if request.method == 'POST':

        if (existingUser.email != request.POST['email']):
            try:
                user = User.objects.get(email = request.POST['email'])
                messages.warning(request, 'Email address already exist')
                return redirect("editProfile")
            except User.DoesNotExist:
                existingUser.email = request.POST['email']
        
        try:
           Pnumber1 =  Pnumber.objects.all().get(user = existingUser)
           Pnumber1.phone_no = request.POST['phonenumber']

        except Pnumber.DoesNotExist:
            Pnumber1 = Pnumber.objects.create(user = existingUser, phone_no = request.POST['phonenumber'])

        existingUser.first_name = request.POST['fname']
        existingUser.last_name = request.POST['lname']

        Pnumber1.save()
        existingUser.save()

        subject = 'Details Updated.'
        message = 'Your account details has been updated successfully.\nFirst Name: ' + existingUser.first_name + '\nLast Name: ' + existingUser.last_name + '\nEmail: ' + existingUser.email + '\nPhone Number: ' + Pnumber1.phone_no
        sendEmail(existingUser.email, subject, message)

        messages.success(request, "User details updated successfully")

    return render(request, 'user/editProfile.html', {"user": existingUser, "phone_no": Pnumber1})

@login_required(login_url = "/staff/")
def dashboard(request):

    if request.user.is_staff == False:
        return HttpResponse("Access Denied")

    rooms = Rooms.objects.all().order_by("hotel__city", "hotel__name")

    totalRooms = len(rooms)
    availableRooms = len(rooms.filter(status = 'Available'))
    unavailableRooms = len(rooms.filter(status = 'Not Available'))
    reserved = len(Reservation.objects.all())
    bookings = len(Reservation.objects.filter(status = 'Booked'))

    cities = Hotels.objects.values_list('city', flat = True).distinct().order_by()

    if request.method == "POST":
        filter = request.POST['filter']

        if filter != "allRooms":
            data = request.POST['data']

            if(filter == "capacity"):
                rooms = Rooms.objects.filter(capacity = data).order_by("hotel__city", "hotel__name")
            
            elif(filter == "city"):
                rooms = Rooms.objects.filter(hotel__city = data).order_by("hotel__city", "hotel__name")
            
            elif(filter == "hotel"):
                rooms = Rooms.objects.filter(hotel__name = data).order_by("hotel__city", "hotel__name")

            elif(filter == "hotelType"):

zevoyo/myApp/templates/user/bookRoom.html
{% extends 'basic.html' %} {% block title %} Book Room {% endblock title %} {% block body %}

<div class="container">
    <div class="col-md-6 col-lg-6 col-xl-6 col-sm-12 mx-auto my-4">

        <form action="/myApp/user/book-room/book/" method="POST">
            {% csrf_token %} {% load app_tags %}

            <div class="form-group">
                <label for="hotel">Hotel: </label>
                <input type="text" class="form-control" id="hotel" name="hotel" disabled value="{{room.hotel.name}}">
            </div>

            <div class="form-group">
                <label for="location">Location: </label>
                <input type="text" class="form-control" id="location" name="location" disabled value="{{room.hotel.city}}">
            </div>

            <div class="form-group">
                <label for="name">Name: </label>
                <input type="text" class="form-control" id="name" name="name" required="true" value="{{request.user}}">
            </div>

            <div class="form-group">
                <label for="email">Email: </label>
                <input type="text" class="form-control" id="email" name="email" required="true" value="{{request.user.email}}">
            </div>

            <div class="form-group">
                <label for="person">Person: </label>
                <input type="text" class="form-control" id="person" name="person" min="1" max="{{room.capacity}}" required="true" value="{{room.capacity}}">
            </div>

            <div class="form-group">
                <label for="check-in">Check-in: </label>
                <input type="date" class="form-control" id="check-in" name="checkIn" min={%todays_date%} max={%max_date%} placeholder="Check In" required="true">
            </div>

            <div class="form-group">
                <label for="check-out">Check-out: </label>
                <input type="date" class="form-control" id="check-out" name="checkOut" min={%tomorrow%} max={%max_date%} placeholder="Check Out" required="true">
            </div>

            <div class="form-group">
                <label for="room-type">Room Type: </label>
                <input type="text" class="form-control" id="room-type" name="roomtype" disabled value="{{room.get_roomType_display}}">
            </div>

            <div class="form-group">
                <label for="price">Price: </label>
                <input type="text" class="form-control" id="price" name="price" disabled value="{{room.price}}">
            </div>

            <button type="submit" class="btn btn-primary">Book Now</button>
            <input type="hidden" name="roomId" value="{{room.id}}">
        </form>

    </div>
</div>

{% endblock body %}

zevoyo/myApp/templates/user/editProfile.html
{% extends 'basic.html' %} {% block title %}Edit Profile {% endblock title %} {% block body %}

<br/><br/>

<div class="form-group">
    {% csrf_token %}

    <p class="text-center text-dark" style="font-weight: 700;font-size: 30px;">Edit Profile</p>
    <div class="container">

        <div style="width: 50%;margin-right: auto;margin-left: auto;">
            <div class="col-md-12 col-lg-12 col-xlg-12 col-sm-12">

                <form action="/myApp/user/editProfile/" method="post">
                    {%csrf_token%}
                    <div class="form-group">
                        <label for="fname">First Name:</label>
                        <input type="text" class="form-control " id="fname" placeholder="Enter your first name" name="fname" value="{{user.first_name}}">
                    </div>
                    <div class="form-group">
                        <label for="lname">Last Name:</label>
                        <input type="text" class="form-control " id="lname" placeholder="Enter your last name" name="lname" value="{{user.last_name}}">
                    </div>
                    <div class="form-group">
                        <label for="username1">Username:</label>
                        <input type="text" class="form-control " id="username1" placeholder="Enter your username" name="username1" disabled value="{{user.username}}">
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="text" class="form-control " id="email" placeholder="Enter your email id" name="email" value="{{user.email}}">
                    </div>
                    <div class="form-group">
                        <label for="phonenumber">Phone Number:</label>
                        <input type="text" class="form-control " id="phonenumber" placeholder="Enter your phone number" name="phonenumber" value="{{phone_no.phone_no}}">
                    </div>

                    <button type="submit" class="btn btn-success">Update Profile</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

zevoyo/myApp/templates/user/login.html
{% extends 'basic.html' %} {% load static %} {% block title %}Login {% endblock title %} {% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'myApp/style/login.css'%}">{% endblock css %} {% block body %}
<!--Cards starts here-->
<div class="container py-5">

    <!--login and signup tab starts here -->
    <section>
        <div class="card w-50 mx-auto">
            <div class="card-title bg-light ">
                <div class="container mt-3 mx-auto">

                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs justify-content-center w-100 " style="width:358px">

                        <li class="nav-item">
                            <a class="nav-link active " data-toggle="tab" href="#home" style="width:158px">Login</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#menu1" style="width:158px">Signup</a>
                        </li>
                    </ul>

                </div>
            </div>

            <div class="card-body">

                <!-- Tab panes -->
                <div class="tab-content">
                    <div id="home" class="container tab-pane active">
                        <p class="text-center text-dark">User login form</p>
                        <div class="container">

                            <div class="row">
                                <div class="col-md-12 col-lg-12 col-xlg-12 col-sm-12">

                                    <form action="/myApp/user/login/" method="post">
                                        {%csrf_token%}
                                        <div class="form-group">
                                            <label for="username">Username:</label>
                                            <input type="text" class="form-control " id="username" placeholder="Enter email" name="username">
                                        </div>
                                        <div class="form-group">
                                            <label for="pwd">Password:</label>
                                            <input type="password" class="form-control" id="password" placeholder="Enter password" name="password">
                                            <span toggle="#password" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Login</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="menu1" class="container tab-pane fade">
                        <p class="text-center text-dark">User Signup form</p>
                        <div class="container">

                            <div class="row">
                                <div class="col-md-12 col-lg-12 col-xlg-12 col-sm-12">

                                    <form action="/myApp/user/signup/" method="post">
                                        {%csrf_token%}
                                        <div class="form-group">
                                            <label for="email">Email:</label>
                                            <input type="text" class="form-control " id="email" placeholder="Enter email id" name="email">
                                        </div>
                                        <div class="form-group">
                                            <label for="username">Username:</label>
                                            <input type="text" class="form-control " id="username" placeholder="Enter Username" name="username">
                                        </div>

                                        <div class="form-group">
                                            <label for="pwd">Password:</label>
                                            <input type="password" class="form-control" id="password1" placeholder="Enter password" name="password1">
                                            <span toggle="#password1" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                                        </div>
                                        <div class="form-group">
                                            <label for="pwd">Confirm Password:</label>
                                            <input type="password" class="form-control " id="password2" placeholder="Confirm password" name="password2">
                                            <span toggle="#password2" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                                        </div>

                                        <button type="submit" class="btn btn-primary">Sign Up</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>
    <!--Login and logout tab ends here-->
    </div>

    <!--Cards ends here-->
    {% endblock body %} {% block js %}
    <script src="{% static '/myApp/script/togglePassword.js' %}"></script>
    {% endblock js %}

zevoyo/myApp/templates/user/mybookings.html
{% extends 'basic.html' %} {% block title %} Dashboard {% endblock title %} {% load static %} {% load app_tags %} {% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'myApp/style/dashboard.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'myApp/style/common.css'%}"> {% endblock css %} {% block body %}
<br>
<h3 class="text-center  text-success">My Bookings </h3>
<br>

<form action="/myApp/user/bookings/" method="POST" class="all-booking">
    {% csrf_token %}
    <div class="form-group">
        <select class="form-control" id="filter" name="filter">
            <option value="allUserBookings">All Bookings</option>
            <option value="checkIn">Check-In</option>
            <option value="checkOut">Check-Out</option>
            <option value="city">City</option>
            <option value="hotel">Hotel</option>
            <option value="hotelType">Hotel Type</option>
            <option value="roomType">Room Type</option>
            <option value="statusBookings">Booking Status</option>
        </select>
    </div>

    <div class="form-group" id="div-data">

    </div>

    <div class="form-group">
        <input type="submit" value="Filter" class="form-control btn btn-warning">
    </div>
</form>

<br>

<table class="table">
    <thead>
        <th>City</th>
        <th>Hotel</th>
        <th>Hotel Type</th>
        <th>Room Type</th>
        <th>Check in</th>
        <th>Check out</th>
        <th>Price</th>
        <th>Status</th>
        <th>Cancel Booking</th>
    </thead>
    {% for booking in bookings %}
    <tr>
        <td>{{booking.room.hotel.city}}</td>
        <td>{{booking.room.hotel.name}}</td>
        <td> {{ booking.room.hotel.type }} </td>
        <td> {{ booking.room.get_roomType_display }} </td>
        <td>{{booking.checkIn}}</td>
        <td>{{booking.checkOut}}</td>
        <td>{{booking.room.price}}</td>
        <td>{{booking.get_status_display}}</td>
        <td>
            <form action="/myApp/booking/cancel/" method="POST">
                {% csrf_token %} {% if booking.cancel and booking.status == 'Booked' %}
                <button type="submit" class="btn btn-danger">Cancel</button> {% else %}
                <button type="submit" class="btn btn-danger" disabled>Cancel</button> {% endif %}
                <input type="hidden" name="bookingId" value="{{booking.id}}">
            </form>
        </td>
    </tr>
    {% endfor %}


</table>
{% endblock body %} {% block js %}
<script src="{% static '/myApp/script/filter.js' %}"></script>
{% endblock js %}